name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: Compile source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: next-7
      - name: Use Node.js v18
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          cache: pnpm
          node-version: 18
      - name: Install Dependencies
        run: pnpm install
      - name: Generate Prisma
        run: pnpm prisma generate
      - name: Build Code
        run: pnpm build

  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: next-7
      - name: Use Node.js v18
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          cache: pnpm
          node-version: 18
      - name: Install Dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm rome check src test
